AWSTemplateFormatVersion: "2010-09-09"

Description: "A stack containing the resources to serve the InnoLab-Frontend-${ENV} assets. This stack will provision "

Parameters:
  environmentName:
    Type: String
    Default: Dev
  applicationName:
    Type: String
    Default: innolab

Mappings:
  SubEnvDomainMap:
    Dev: 
      subdomainEnv:  "-dev"
    Test: 
      subdomainEnv: "-test"
    Staging: 
      subdomainEnv: "-staging"
    Prod: 
      subdomainEnv: ""
    
Resources:
  FrontendBucketLogs:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Sub 
        - "${applicationName}-frontend${environment}-logs"
        - environment: 
            Fn::FindInMap:
              - SubEnvDomainMap
              - !Ref environmentName
              - subdomainEnv

  FrontendDeployBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub 
        - "${applicationName}-frontend${environment}-deployment"
        - environment:
            Fn::FindInMap:
              - SubEnvDomainMap
              - !Ref environmentName
              - subdomainEnv
      LoggingConfiguration:
        DestinationBucketName: !Ref FrontendBucketLogs
        LogFilePrefix: 'cdn/'
      WebsiteConfiguration:
        IndexDocument: 'index.html'

  CoverageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub 
        - "${applicationName}-coverage${environment}"
        - environment:
            Fn::FindInMap:
              - SubEnvDomainMap
              - !Ref environmentName
              - subdomainEnv
      LoggingConfiguration:
        DestinationBucketName: !Ref FrontendBucketLogs
        LogFilePrefix: 'cov/'
      WebsiteConfiguration:
        IndexDocument: 'index.html'

  DeployBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendDeployBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Principal: '*'
            Resource: !Sub '${FrontendDeployBucket.Arn}/*'
    DependsOn:
      - FrontendDeployBucket
  
  CoverageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CoverageBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Principal: '*'
            Resource: !Sub '${CoverageBucket.Arn}/*'
    DependsOn:
      - FrontendDeployBucket

Outputs:
  DeployBucketID:
    Value: !Ref FrontendDeployBucket
    Description: Resource ID of the frontend deployment bucket
    Export:
      Name: !Sub ${AWS::StackName}-FrontendDeployBucketID
  DeployBucketDomain:
    Value: !GetAtt FrontendDeployBucket.DomainName
    Description: Domain name of the frontend deployment bucket
    Export:
      Name: !Sub ${AWS::StackName}-FrontendDeployBucketDomain
  CoverageBucketID:
    Value: !Ref CoverageBucket
    Description: Resource ID of the frontend deployment bucket
    Export:
      Name: !Sub ${AWS::StackName}-CoverageBucketID
  CoverageBucketDomain:
    Value: !GetAtt CoverageBucket.DomainName
    Description: Domain name of the frontend deployment bucket
    Export:
      Name: !Sub ${AWS::StackName}-CoverageBucketDomain
  LogBucketID:
    Value: !Ref FrontendBucketLogs
    Description: Resource ID of the frontend deployment bucket
    Export:
      Name: !Sub ${AWS::StackName}-FrontendLogBucketID
  LogBucketDomain:
    Value: !GetAtt FrontendDeployBucket.DomainName
    Description: Resource ID of the frontend deployment bucket
    Export:
      Name: !Sub ${AWS::StackName}-FrontendLogBucketDomain