trigger:
- master

variables:
- group: Deploy

jobs:
  - job: LintValidation
    condition: not(eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          pip install -r requirements.txt
        displayName: Install CloudFormation linter
      - script: |
          cfn-lint ./templates/**/*.yml
        displayName: Lint templates
        
  - job: VulnerabilityScan
    condition: not(eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: LintValidation
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          npm install snyk -g
          snyk config set org=$SNYK_ORG_ID
          snyk auth $SNYK_TOKEN
        displayName: Install SNYK CLI scanner
        env:
          NODE_VERSION: 14.0.0
          SNYK_TOKEN: $(SNYK_TOKEN)
          SNYK_ORG_ID: $(SNYK_ORG_ID)
      - script: |
          snyk iac test ./templates/** \
                          --severity-threshold="critical"
        displayName: Scan templates for vulnerabilities

  - job: ManualApproval
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    dependsOn: VulnerabilityScan
    pool: server
    steps:
    - task: ManualValidation@0
      continueOnError: false
      enabled: true
      timeoutInMinutes: 30
      inputs:
        notifyUsers: |
          grant@cumberland-cloud.com
        instructions: 'Validate and approve infrastructure configuration before deployment'
        onTimeout: 'reject'

  - deployment: DeployInnoLab
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    dependsOn: ManualApproval
    displayName: DeployResources
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'AWS'
    strategy: 
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: |
              pip install -r ./src/requirements.txt
            displayName: Install deployment dependencies
          - script: |
              python ./src/deploy/deployer.py deploy
            displayName: Deploy cloud resources
            env:
              APPLICATION: $(APPLICATION)
              ENVIRONMENT: $(ENVIRONMENT)
              DOMAIN: $(DOMAIN)
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              HOSTED_ZONE_ID: $(HOSTED_ZONE_ID)
              CERTIFICATE_ID: $(CERTIFICATE_ID)
              PIPELINE_USER: $(PIPELINE_USER)
