AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack for a serverless QLDB ledger"

Parameters:
    ledgerName:
      Type: String
      Default: laboratory
      Description: Name of the QLDB Ledger provisioned
    environmentName:
      Type: String
      Default: Dev
      Description: Environment into which the resources are deploying
    applicationName:
      Type: String
      Default: innolab
      Description: Namespace of the application resources

Resources:
  QLDBLedger:
    Type: AWS::QLDB::Ledger
    Properties:
      Name: !Sub ${applicationName}-${environmentName}-${ledgerName}
      PermissionsMode: STANDARD
      DeletionProtection: false
      Tags:
        - Key: Environment
          Value: !Ref environmentName
        - Key: Application
          Value: !Ref applicationName
   

